name: Hugo Build on PR

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

  workflow_dispatch:

jobs:
  build:
    name: PR Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_RELEASE }}
          extended: true
        env:
          HUGO_RELEASE: 'latest'
      - name: Check Hugo installation
        run: hugo env
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Build website with Hugo
        run: hugo --minify --printI18nWarnings --templateMetrics --logLevel info
